from typing import Dict, Any, Optional
import json
from datetime import datetime
from app.core.config import settings
from app.core.logging_config import get_logger
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content

logger = get_logger(__name__)

class EmailService:
    def __init__(self):
        # Configuration for email delivery
        self.recipient_email = settings.EMAIL_RECIPIENT
        self.email_from = settings.EMAIL_FROM
        self.email_from_name = settings.EMAIL_FROM_NAME
        self.sendgrid_enabled = settings.SENDGRID_ENABLED
        self.sendgrid_api_key = settings.SENDGRID_API_KEY
        
        # Initialize SendGrid client if available
        if self.sendgrid_enabled and self.sendgrid_api_key:
            try:
                self.sendgrid_client = SendGridAPIClient(self.sendgrid_api_key)
            except Exception as e:
                self.sendgrid_client = None
        else:
            self.sendgrid_client = None

    def send_user_data(self, user_data: Dict[str, Any]) -> Dict[str, Any]:
        """Send user data via email using SendGrid API"""
        
        try:
            # Create structured email content
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
            
            # Plain text version
            text_content = f"""
AI ENGINEER ASSESSMENT - USER DATA COLLECTED

A new user has completed the chatbot interaction and provided their information:

=== USER INFORMATION ===
Name: {user_data.get('name', 'Not provided')}
Email: {user_data.get('email', 'Not provided')}
Income: {user_data.get('income', 'Not provided')}

=== SYSTEM INFORMATION ===
Collection Timestamp: {timestamp}
Session: Insomniac Hedge Fund AI Assessment

=== RAW DATA (JSON) ===
{json.dumps(user_data, indent=2)}
"""

            # HTML version for better formatting
            html_content = f"""
<html>
<body>
    <h2 style="color: #2c3e50;">🤖 AI ENGINEER ASSESSMENT - USER DATA COLLECTED</h2>
    
    <p>A new user has completed the chatbot interaction and provided their information:</p>
    
    <h3 style="color: #34495e;">👤 User Information</h3>
    <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
        <tr style="background-color: #f8f9fa;">
            <td style="border: 1px solid #dee2e6; padding: 8px; font-weight: bold;">Name:</td>
            <td style="border: 1px solid #dee2e6; padding: 8px;">{user_data.get('name', 'Not provided')}</td>
        </tr>
        <tr>
            <td style="border: 1px solid #dee2e6; padding: 8px; font-weight: bold;">Email:</td>
            <td style="border: 1px solid #dee2e6; padding: 8px;">{user_data.get('email', 'Not provided')}</td>
        </tr>
        <tr style="background-color: #f8f9fa;">
            <td style="border: 1px solid #dee2e6; padding: 8px; font-weight: bold;">Income:</td>
            <td style="border: 1px solid #dee2e6; padding: 8px;">{user_data.get('income', 'Not provided')}</td>
        </tr>
    </table>
    
    <h3 style="color: #34495e;">⚙️ System Information</h3>
    <ul>
        <li><strong>Collection Timestamp:</strong> {timestamp}</li>
        <li><strong>Database ID:</strong> {user_data.get('id', 'Unknown')}</li>
        <li><strong>Session:</strong> Insomniac Hedge Fund AI Assessment</li>
    </ul>
    
    <h3 style="color: #34495e;">📋 Raw Data (JSON)</h3>
    <pre style="background-color: #f8f9fa; padding: 10px; border-radius: 4px; overflow-x: auto;">
{json.dumps(user_data, indent=2)}
    </pre>
    
    <hr style="margin: 20px 0;">
    <p style="color: #6c757d; font-size: 12px;">
        This email was automatically generated by the AI chatbot system as part of <strong>Layer 4 (Structured Output Delivery)</strong> of the AI Engineer Assessment.
    </p>
    <p style="color: #6c757d; font-size: 12px;">
        <strong>Best regards,</strong><br>
        AI Chatbot System<br>
        Insomniac Hedge Fund Guy Assessment
    </p>
</body>
</html>
"""

            # Send via SendGrid API (primary method)
            if self.sendgrid_enabled and self.sendgrid_client:
                result = self._send_via_sendgrid(user_data, text_content, html_content)
                if result.get('success'):
                    return {
                        "success": True,
                        "message": f"Email sent successfully to {self.recipient_email}",
                        "method": "sendgrid"
                    }
                else:
                    error_msg = result.get('error', 'Unknown error')
                    return {
                        "success": False,
                        "message": f"Email delivery failed via SendGrid: {error_msg}",
                        "error": error_msg
                    }
            else:
                self._log_email_content(user_data, text_content)
                return {
                    "success": False,
                    "message": "SendGrid is not available or disabled",
                    "error": "SendGrid not configured"
                }

        except Exception as e:
            return {"success": False, "error": str(e)}

    def _send_via_sendgrid(self, user_data: Dict[str, Any], text_content: str, html_content: str) -> Dict[str, Any]:
        """Send email via SendGrid API"""
        try:            
            if not self.sendgrid_client:
                return {"success": False, "method": "sendgrid", "error": "SendGrid client not initialized"}
            
            from_email = Email(self.email_from, name=self.email_from_name)
            to_email = To(self.recipient_email)
            subject = f"AI Assessment - User Data: {user_data.get('name', 'Unknown')}"
            
            message = Mail(
                from_email=from_email,
                to_emails=to_email,
                subject=subject,
                plain_text_content=text_content,
                html_content=html_content
            )
            
            response = self.sendgrid_client.send(message)
            status_code = response.status_code
            
            if status_code in [200, 201, 202]:
                return {
                    "success": True,
                    "method": "sendgrid",
                    "message": f"Email sent successfully to {self.recipient_email}",
                    "recipient": self.recipient_email,
                    "status_code": status_code
                }
            else:
                error_msg = f"SendGrid API returned status {status_code}: {response.body}"
                return {
                    "success": False,
                    "method": "sendgrid",
                    "error": error_msg,
                    "status_code": status_code
                }
                
        except Exception as e:
            return {"success": False, "method": "sendgrid", "error": str(e)}
    
    def _log_email_content(self, user_data: Dict[str, Any], email_content: str) -> None:
        """Log email content as fallback when SendGrid is unavailable"""